version: "3"
services:
  playtopia-dev:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: c-playtopia-dev
    networks:
      - default
    ports:
      - "80:8000"
      # - "9000:9000"    
    