version: "2"
services:
  playtopia-dev:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: c-playtopia-dev
    ports:
      - "80:8000"
      # - "9000:9000"
    volumes:
      - ./:/usr/src/app/wwwroot
    working_dir: /usr/src/app