definitions:
  app.Response:
    properties:
      data: {}
      error:
        type: string
      errors: {}
      msg:
        type: string
    type: object
  models.FileResponse:
    properties:
      file_name:
        description: ID       int    `json:"id"`
        type: string
      file_path:
        type: string
      file_type:
        type: string
    type: object
  models.ForgotForm:
    properties:
      account:
        type: string
    type: object
  models.GroupForm:
    properties:
      GroupCode:
        type: string
      description:
        type: string
    type: object
  models.HolidayForm:
    properties:
      description:
        type: string
      holiday_date:
        type: string
    type: object
  models.LoginForm:
    properties:
      account:
        type: string
      pwd:
        type: string
    type: object
  models.RegisterForm:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone_no:
        type: string
    type: object
  models.ResetPasswd:
    properties:
      account:
        type: string
      confirm_pwd:
        type: string
      pwd:
        type: string
    type: object
  models.ResponseModelList:
    properties:
      data: {}
      last_page:
        type: integer
      message:
        type: string
      page:
        type: integer
      status:
        type: integer
      total:
        type: integer
    type: object
  models.SosmedForm:
    properties:
      access_token:
        type: string
      email:
        type: string
      name:
        type: string
    type: object
  models.VerifyForgotForm:
    properties:
      access_token:
        type: string
      email:
        type: string
      otp:
        type: string
      phone_no:
        type: string
    type: object
  models.VerifyForm:
    properties:
      access_token:
        type: string
      email:
        type: string
      phone_no:
        type: string
    type: object
info:
  contact:
    email: nuryantofattih@gmail.com
    name: Nuryanto
    url: https://www.linkedin.com/in/nuryanto-1b2721156/
  description: Backend REST API for golang nuryanto2121
  title: Base 369
  version: "1.0"
paths:
  /v1/account/fileupload:
    delete:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: 'req param #pakai yang file_path ajah'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.FileResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: Delete FileUpload
      tags:
      - FileUpload
    post:
      consumes:
      - multipart/form-data
      description: Upload file
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: account image
        in: formData
        name: upload_file
        required: true
        type: file
      - description: path images
        in: formData
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: File Upload
      tags:
      - FileUpload
  /v1/cms/change-password:
    post:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: account set from verify forgot otp
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.ResetPasswd'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Change Password
      tags:
      - Auth
  /v1/cms/check-phone-no/{phone_no}:
    get:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: phone no
        in: path
        name: phone_no
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: get profile
      tags:
      - Auth
  /v1/cms/forgot:
    post:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.ForgotForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Forgot Password
      tags:
      - Auth
  /v1/cms/groups:
    get:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Version Apps
        in: header
        name: Version
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: PerPage
        in: query
        name: perpage
        required: true
        type: integer
      - description: Search
        in: query
        name: search
        type: string
      - description: InitSearch
        in: query
        name: initsearch
        type: string
      - description: SortField
        in: query
        name: sortfield
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseModelList'
      summary: GetList Groups
      tags:
      - Groups
    post:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Version Apps
        in: header
        name: Version
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: this model set from firebase
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.GroupForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Create Groups
      tags:
      - Groups
  /v1/cms/groups/{id}:
    delete:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Version Apps
        in: header
        name: Version
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Delete Groups
      tags:
      - Groups
    get:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Version Apps
        in: header
        name: Version
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: GetById Groups
      tags:
      - Groups
    put:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Version Apps
        in: header
        name: Version
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: this model set from firebase
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.GroupForm'
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Update Groups
      tags:
      - Groups
  /v1/cms/holidays:
    get:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Version Apps
        in: header
        name: Version
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: Page
        in: query
        name: page
        required: true
        type: integer
      - description: PerPage
        in: query
        name: perpage
        required: true
        type: integer
      - description: Search
        in: query
        name: search
        type: string
      - description: InitSearch
        in: query
        name: initsearch
        type: string
      - description: SortField
        in: query
        name: sortfield
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseModelList'
      summary: GetList Holidays
      tags:
      - Holidays
    post:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Version Apps
        in: header
        name: Version
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: this model set from firebase
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.HolidayForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Create Holidays
      tags:
      - Holidays
  /v1/cms/holidays/{id}:
    delete:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Version Apps
        in: header
        name: Version
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Delete Holidays
      tags:
      - Holidays
    get:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Version Apps
        in: header
        name: Version
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: GetById Holidays
      tags:
      - Holidays
    put:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Version Apps
        in: header
        name: Version
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: this model set from firebase
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.HolidayForm'
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Update Holidays
      tags:
      - Holidays
  /v1/cms/login:
    post:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Version Apps
        in: header
        name: Version
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Login
      tags:
      - Auth
  /v1/cms/logout:
    post:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      security:
      - ApiKeyAuth: []
      summary: logout
      tags:
      - Auth
  /v1/cms/register:
    post:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: Body with file zip
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.RegisterForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Register
      tags:
      - Auth
  /v1/cms/sosmed:
    post:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: this model set from firebase
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.SosmedForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: auth from sosmed sdk firebase if login then get token and data user
        else OTP
      tags:
      - Auth
  /v1/cms/verify-forgot-otp:
    post:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.VerifyForgotForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Verify OTP Forgot
      tags:
      - Auth
  /v1/cms/verify-register-otp:
    post:
      parameters:
      - description: Device Type
        in: header
        name: Device-Type
        required: true
        type: string
      - description: Language Apps
        in: header
        name: Language
        required: true
        type: string
      - description: 'req param #changes are possible to adjust the form of the registration
          form from frontend'
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/models.VerifyForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
      summary: Verify OTP Register
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
